### PR TITLE
19. Refactor existing code into MVC

### LINKED ISSUE #40: 19. Refactor code to MVC pattern
As a structured developer, I would like to restructure the application with the MVC pattern since it will make the code a lot more readable and maintainable in the future.

Acceptance criterias:

- [ ] Refactor code using the MVC pattern
- [ ] Models, Views and Controller classes should reside in their respective java packages.

### LINKED ISSUE #45: 19.1 Refactor code to MVC pattern

### PR DESCRIPTION
**Pull request by Erik142**
Closes #45. As #45 is the only task in #40, this also closes #40.

The existing code, including PR #63 has been converted into what the assigned developers (me and @valeria9090 ) would say is a reasonable MVC pattern.

Right now the model classes contain only data that the view (Activity) needs. The controller classes are doing all the heavy lifting otherwise. If we move the "heavy lifting" into the model classes, I am afraid that they will not be as easily testable, but please come with suggestions so that we can discuss how to proceed together 👍🏻 

There are still some small things that need to be done in order for this PR to be considered "done", for example updating javadoc in some of the files and moving the handler classes into their appropriate java package. However, @valeria9090 and I feel that this is a good enough candidate for being reviewed a first time.

The PR itself **might** be a bit too large for one reviewer to take on, so if more of you want to take a look at it and give us your comments, please, go ahead! 😄 

Merged with the latest version of master, so no merge conflicts should be available at the time of creating this PR.

### CODE REVIEW

**Comment by danbrn** [comment]
I'll take a look.

**Review by danbrn — APPROVED** [review]
DISCLAIMER: I'm no MVC expert, and I haven't examined all the code in great detail.

It builds, it runs, and I'm comfortable with using this design. Good job!

I found some minor issues with stuff not related to the refactor, though, so I might create a user story or two about that when I have more time.

**Comment by Erik142** [comment]
Added the final commits to this PR, if everything looks good, it should be able to be merged now 👍🏻

**Review by danbrn — APPROVED** [review]
Still looks good. I'll go ahead and merge.

**Pull request merged**
